dev:
  env: dev
  catalog: acmi_edw_dev
  landing_volume: /Volumes/{catalog}/{raw_schema}/landing_volume
  raw_schema: edw_raw
  bronze_schema: edw_bronze
  silver_schema: edw_silver
  gold_schema: edw_gold
  
secrets:
  default_scope: dev_secrets
  scopes:
    database: dev_db_secrets



# global:
#   # Company-wide standards
#   company: mehdi_corp
#   region: us-east-1
#   timezone: UTC
#   default_file_format: delta
#   default_table_properties:
#     delta.enableChangeDataFeed: "true"
#     delta.autoOptimize.optimizeWrite: "true"